# Generated by Django 5.2.8 on 2025-12-12 23:39

import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Sube una imagen del producto (opcional)', null=True, upload_to=inventario.models.upload_to_productos, verbose_name='Imagen del Producto'),
        ),
    ]
