# Generated by Django 5.2.8 on 2025-12-15 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_proveedor_factura_itemfactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_promo',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Precio promocional (opcional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Promo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unidad'),
        ),
    ]
