# Generated by Django 5.2.8 on 2025-12-16 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto_precio_promo_alter_producto_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Agregado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_favoritos', to='inventario.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto Favorito',
                'verbose_name_plural': 'Productos Favoritos',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('usuario', 'producto')},
            },
        ),
    ]
