# Generated by Django 5.2.8 on 2025-12-18 23:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_productofavorito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Precio al que se compró el producto (para calcular margen)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Venta'),
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('perdida', 'Pérdida'), ('devolucion', 'Devolución')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('motivo', models.CharField(choices=[('compra', 'Compra a Proveedor'), ('venta', 'Venta'), ('ajuste_inventario', 'Ajuste de Inventario'), ('perdida', 'Pérdida/Rotura'), ('devolucion_cliente', 'Devolución de Cliente'), ('devolucion_proveedor', 'Devolución a Proveedor'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], max_length=50, verbose_name='Motivo')),
                ('stock_anterior', models.IntegerField(verbose_name='Stock Anterior')),
                ('stock_nuevo', models.IntegerField(verbose_name='Stock Nuevo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.factura', verbose_name='Factura Relacionada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha'],
            },
        ),
    ]
