# Generated by Django 5.2.8 on 2025-12-18 23:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_producto_precio_compra_alter_producto_precio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venta', models.CharField(max_length=50, unique=True, verbose_name='Número de Venta')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Venta')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Subtotal')),
                ('descuento', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto')], default='efectivo', max_length=20, verbose_name='Método de Pago')),
                ('monto_recibido', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Monto Recibido')),
                ('cambio', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Cambio')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('cancelada', models.BooleanField(default=False, verbose_name='Venta Cancelada')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Subtotal')),
                ('stock_anterior', models.IntegerField(default=0, verbose_name='Stock Anterior')),
                ('stock_despues', models.IntegerField(default=0, verbose_name='Stock Después')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Item de Venta',
                'verbose_name_plural': 'Items de Venta',
                'ordering': ['id'],
            },
        ),
    ]
