# Generated by Django 5.2.8 on 2025-12-19 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_cotizacion_itemcotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('vista', models.BooleanField(default=False, verbose_name='Vista')),
                ('notificada', models.BooleanField(default=False, verbose_name='Notificada')),
                ('stock_anterior', models.IntegerField(verbose_name='Stock Anterior')),
                ('stock_actual', models.IntegerField(verbose_name='Stock Actual')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_stock', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Notificación de Stock',
                'verbose_name_plural': 'Notificaciones de Stock',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha', 'vista'], name='inventario__fecha_b32b55_idx')],
            },
        ),
    ]
