# Generated by Django 5.2.8 on 2025-12-19 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_venta_es_credito_alter_cotizacion_cliente_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Búsqueda')),
                ('tipo', models.CharField(choices=[('producto', 'Producto'), ('cliente', 'Cliente'), ('venta', 'Venta'), ('cotizacion', 'Cotización'), ('global', 'Búsqueda Global')], default='global', max_length=20, verbose_name='Tipo')),
                ('resultados', models.IntegerField(default=0, verbose_name='Cantidad de Resultados')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busquedas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Búsqueda',
                'verbose_name_plural': 'Historial de Búsquedas',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario', '-fecha'], name='inventario__usuario_b088ff_idx'), models.Index(fields=['query'], name='inventario__query_335d37_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('ver', 'Ver'), ('exportar', 'Exportar'), ('imprimir', 'Imprimir'), ('login', 'Iniciar Sesión'), ('logout', 'Cerrar Sesión'), ('buscar', 'Buscar'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Acción')),
                ('modulo', models.CharField(choices=[('producto', 'Producto'), ('cliente', 'Cliente'), ('venta', 'Venta'), ('cotizacion', 'Cotización'), ('factura', 'Factura'), ('proveedor', 'Proveedor'), ('almacen', 'Almacén'), ('compra', 'Compra'), ('usuario', 'Usuario'), ('sistema', 'Sistema')], max_length=20, verbose_name='Módulo')),
                ('objeto_id', models.IntegerField(blank=True, null=True, verbose_name='ID del Objeto')),
                ('objeto_tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Objeto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos Nuevos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acción',
                'verbose_name_plural': 'Logs de Acciones',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario', '-fecha'], name='inventario__usuario_5e3aaf_idx'), models.Index(fields=['modulo', 'tipo_accion'], name='inventario__modulo_325d3b_idx'), models.Index(fields=['-fecha'], name='inventario__fecha_211474_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('stock_bajo', 'Stock Bajo'), ('cuenta_vencida', 'Cuenta Vencida'), ('orden_pendiente', 'Orden Pendiente'), ('sistema', 'Sistema'), ('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('url_relacionada', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Relacionada')),
                ('datos_adicionales', models.JSONField(blank=True, null=True, verbose_name='Datos Adicionales')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha', 'leida'],
                'indexes': [models.Index(fields=['usuario', 'leida', '-fecha'], name='inventario__usuario_f27130_idx')],
            },
        ),
    ]
