# Generated by Django 5.2.8 on 2025-12-19 19:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_agregar_modelos_mejoras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_devolucion', models.CharField(max_length=50, unique=True, verbose_name='Número de Devolución')),
                ('tipo_devolucion', models.CharField(choices=[('completa', 'Devolución Completa'), ('parcial', 'Devolución Parcial')], max_length=20, verbose_name='Tipo de Devolución')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesada', 'Procesada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('monto_devolver', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Monto a Devolver')),
                ('metodo_reembolso', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('credito', 'Crédito en Cuenta')], max_length=20, verbose_name='Método de Reembolso')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo de la Devolución')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to='inventario.cliente', verbose_name='Cliente')),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_procesadas', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='inventario.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio Anterior')),
                ('precio_nuevo', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio Nuevo')),
                ('precio_compra_anterior', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Precio Compra Anterior')),
                ('precio_compra_nuevo', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Precio Compra Nuevo')),
                ('precio_promo_anterior', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Precio Promo Anterior')),
                ('precio_promo_nuevo', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Precio Promo Nuevo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('motivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo del Cambio')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='inventario.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historial de Precios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad a Devolver')),
                ('motivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo Específico')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.devolucion', verbose_name='Devolución')),
                ('item_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.itemventa', verbose_name='Item de Venta')),
            ],
            options={
                'verbose_name': 'Item de Devolución',
                'verbose_name_plural': 'Items de Devolución',
            },
        ),
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ajuste', models.CharField(max_length=50, unique=True, verbose_name='Número de Ajuste')),
                ('tipo_ajuste', models.CharField(choices=[('incremento', 'Incremento'), ('decremento', 'Decremento'), ('correccion', 'Corrección')], max_length=20, verbose_name='Tipo de Ajuste')),
                ('cantidad_anterior', models.IntegerField(verbose_name='Cantidad Anterior')),
                ('cantidad_nueva', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Nueva')),
                ('diferencia', models.IntegerField(help_text='Cantidad a ajustar (positiva o negativa)', verbose_name='Diferencia')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo del Ajuste')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='inventario.producto', verbose_name='Producto')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['producto', 'estado'], name='inventario__product_f2020c_idx'), models.Index(fields=['estado', '-fecha_solicitud'], name='inventario__estado_36f460_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['venta', 'estado'], name='inventario__venta_i_d9d06d_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['estado', '-fecha_solicitud'], name='inventario__estado_723272_idx'),
        ),
        migrations.AddIndex(
            model_name='historialprecio',
            index=models.Index(fields=['producto', '-fecha'], name='inventario__product_22b3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='historialprecio',
            index=models.Index(fields=['-fecha'], name='inventario__fecha_6a715f_idx'),
        ),
    ]
