# Generated by Django 5.2.8 on 2025-12-19 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_devolucion_historialprecio_itemdevolucion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Reporte')),
                ('tipo_reporte', models.CharField(choices=[('ventas', 'Reporte de Ventas'), ('inventario', 'Reporte de Inventario'), ('stock_bajo', 'Productos con Stock Bajo'), ('cuentas_cobrar', 'Cuentas por Cobrar'), ('completo', 'Reporte Completo')], max_length=50, verbose_name='Tipo de Reporte')),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='Formato')),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('personalizado', 'Personalizado')], max_length=20, verbose_name='Frecuencia')),
                ('dia_semana', models.IntegerField(blank=True, help_text='0=Lunes, 6=Domingo (solo para semanal)', null=True, verbose_name='Día de la Semana')),
                ('dia_mes', models.IntegerField(blank=True, help_text='1-31 (solo para mensual)', null=True, verbose_name='Día del Mes')),
                ('hora_envio', models.TimeField(default='09:00', verbose_name='Hora de Envío')),
                ('destinatarios', models.TextField(help_text='Emails separados por comas', verbose_name='Destinatarios')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ultimo_envio', models.DateTimeField(blank=True, null=True, verbose_name='Último Envío')),
                ('proximo_envio', models.DateTimeField(blank=True, null=True, verbose_name='Próximo Envío')),
                ('parametros', models.JSONField(blank=True, help_text='Filtros, rangos de fechas, etc.', null=True, verbose_name='Parámetros Adicionales')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_programados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Reporte Programado',
                'verbose_name_plural': 'Reportes Programados',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['activo', 'proximo_envio'], name='inventario__activo_b5ecdb_idx')],
            },
        ),
    ]
