# Generated by Django 5.2.8 on 2025-12-19 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_reporteprogramado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(help_text='Código único del lote', max_length=100, verbose_name='Número de Lote/Serie')),
                ('fecha_fabricacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Fabricación')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('cantidad_inicial', models.IntegerField(default=0, verbose_name='Cantidad Inicial')),
                ('cantidad_actual', models.IntegerField(default=0, verbose_name='Cantidad Actual')),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación específica dentro del almacén', max_length=200, null=True, verbose_name='Ubicación')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='inventario.almacen', verbose_name='Almacén')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.producto', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='inventario.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código ISO (ej: USD, CLP, EUR)', max_length=3, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre completo de la moneda', max_length=100, verbose_name='Nombre')),
                ('simbolo', models.CharField(help_text='Símbolo de la moneda (ej: $, €, £)', max_length=10, verbose_name='Símbolo')),
                ('tasa_cambio', models.DecimalField(decimal_places=4, default=1.0, help_text='Tasa respecto a la moneda base', max_digits=12, verbose_name='Tasa de Cambio')),
                ('es_base', models.BooleanField(default=False, help_text='Moneda base del sistema', verbose_name='Moneda Base')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='inventario__codigo_80e7f8_idx'), models.Index(fields=['activa'], name='inventario__activa_dda702_idx')],
            },
        ),
        migrations.CreateModel(
            name='CambioMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_anterior', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Tasa Anterior')),
                ('tasa_nueva', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Tasa Nueva')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('motivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='inventario.moneda', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Cambio de Moneda',
                'verbose_name_plural': 'Cambios de Moneda',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('transferencia', 'Transferencia')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('motivo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('ajuste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_lote', to='inventario.ajusteinventario', verbose_name='Ajuste')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.lote', verbose_name='Lote')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_lote', to='inventario.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Movimiento de Lote',
                'verbose_name_plural': 'Movimientos de Lotes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='WidgetDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estadisticas', 'Estadísticas Generales'), ('productos_stock_bajo', 'Productos Stock Bajo'), ('ventas_recientes', 'Ventas Recientes'), ('grafico_ventas', 'Gráfico de Ventas'), ('grafico_productos', 'Gráfico de Productos'), ('notificaciones', 'Notificaciones'), ('calendario', 'Calendario')], max_length=50, verbose_name='Tipo de Widget')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('posicion_x', models.IntegerField(default=0, verbose_name='Posición X')),
                ('posicion_y', models.IntegerField(default=0, verbose_name='Posición Y')),
                ('ancho', models.IntegerField(default=4, help_text='Columnas (1-12)', verbose_name='Ancho')),
                ('alto', models.IntegerField(default=3, help_text='Filas', verbose_name='Alto')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('configuracion', models.JSONField(blank=True, default=dict, help_text='Configuración adicional del widget en formato JSON', verbose_name='Configuración')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets_dashboard', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Widget de Dashboard',
                'verbose_name_plural': 'Widgets de Dashboard',
                'ordering': ['usuario', 'orden', 'posicion_y', 'posicion_x'],
            },
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['producto', 'numero_lote'], name='inventario__product_968407_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['fecha_vencimiento'], name='inventario__fecha_v_d666fe_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['activo'], name='inventario__activo_507114_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('producto', 'numero_lote')},
        ),
        migrations.AddIndex(
            model_name='cambiomoneda',
            index=models.Index(fields=['moneda', '-fecha'], name='inventario__moneda__e77684_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientolote',
            index=models.Index(fields=['lote', '-fecha'], name='inventario__lote_id_32d456_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientolote',
            index=models.Index(fields=['tipo'], name='inventario__tipo_d60973_idx'),
        ),
        migrations.AddIndex(
            model_name='widgetdashboard',
            index=models.Index(fields=['usuario', 'visible'], name='inventario__usuario_777eed_idx'),
        ),
    ]
