# Generated by Django 5.2.8 on 2025-12-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_lote_moneda_cambiomoneda_movimientolote_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='inventario__nombre_2dddb1_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['sku'], name='inventario__sku_814480_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'stock'], name='inventario__activo_1d2b38_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'activo'], name='inventario__categor_c6db1b_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', '-fecha_creacion'], name='inventario__activo_38320c_idx'),
        ),
    ]
