"""
Django settings for control_stock project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Importar dj_database_url solo si está disponible (para producción en Render)
try:
    import dj_database_url
except ImportError:
    dj_database_url = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Para uso local, DEBUG está activo. En producción se configura con variable de entorno.
# Definir DEBUG primero porque se usa en la validación de SECRET_KEY
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
# En producción, SECRET_KEY DEBE estar configurada como variable de entorno
# En desarrollo local, se permite un fallback solo si DEBUG=True
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Solo en desarrollo: usar una clave por defecto (NO SEGURO para producción)
        SECRET_KEY = 'django-insecure-dev-only-_mu8+q+qb_!n$24+1)j4qg-1tom$(f2j13zm8_5uy&bg#za=%#'
        import warnings
        warnings.warn(
            "SECRET_KEY no configurada. Usando clave de desarrollo insegura. "
            "Configura SECRET_KEY como variable de entorno en producción.",
            UserWarning
        )
    else:
        # En producción, fallar si no hay SECRET_KEY
        raise ValueError(
            "SECRET_KEY no configurada. "
            "Configura la variable de entorno SECRET_KEY antes de ejecutar en producción."
        )

# ALLOWED_HOSTS para uso local: localhost, IP local, y red local
# Permite acceso desde el mismo PC y otros dispositivos en la red local
DEFAULT_ALLOWED_HOSTS = 'localhost,127.0.0.1,0.0.0.0,192.168.18.13'
ALLOWED_HOSTS = [host.strip() for host in os.environ.get('ALLOWED_HOSTS', DEFAULT_ALLOWED_HOSTS).split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'drf_spectacular',  # Para documentación Swagger/OpenAPI
    # Local
    'inventario',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Para multi-idioma
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Agregar WhiteNoise middleware solo si está disponible (para producción en Render)
try:
    import whitenoise
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
except ImportError:
    pass

ROOT_URLCONF = 'control_stock.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # Para LANGUAGE_CODE en templates
                'inventario.context_processors.translations',  # Para traducciones personalizadas
            ],
        },
    },
]

WSGI_APPLICATION = 'control_stock.wsgi.application'


# ============================================================================
# CONFIGURACIÓN DE BASE DE DATOS
# ============================================================================
# Para DESARROLLO LOCAL: SQLite (rápido, sin configuración, archivo local)
# Para PRODUCCIÓN: PostgreSQL (mejor rendimiento, escalabilidad)
# ============================================================================

DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL and dj_database_url:
    # PRODUCCIÓN: Usar PostgreSQL si DATABASE_URL está configurada
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # DESARROLLO LOCAL: SQLite optimizado para uso local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            # SQLite ya está optimizado por defecto para desarrollo local
            # No necesita configuración adicional
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'  # Cambiado de 'es-es' a 'es' para coincidir con LANGUAGES

TIME_ZONE = 'America/Santiago'

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Idiomas soportados
LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
    ('pt', 'Português'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Configuración de cookies de idioma
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = 60 * 60 * 24 * 365  # 1 año
LANGUAGE_COOKIE_PATH = '/'
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_SECURE = False  # True en producción con HTTPS
LANGUAGE_COOKIE_HTTPONLY = False
LANGUAGE_COOKIE_SAMESITE = 'Lax'

# Login URL
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Configuración de WhiteNoise para servir archivos estáticos (solo si está disponible)
# En desarrollo local no es necesario, Django sirve los estáticos automáticamente
try:
    import whitenoise
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
except ImportError:
    # En desarrollo local sin WhiteNoise, usar el storage por defecto
    pass

# Media files (Uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CSRF trusted origins para red local
CSRF_TRUSTED_ORIGINS = [
    'http://192.168.18.13:8000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Configuración de seguridad
# En desarrollo local (DEBUG=True): Configuraciones relajadas para facilitar el uso
# En producción (DEBUG=False): Configuraciones estrictas de seguridad

if not DEBUG:
    # Configuraciones de seguridad para PRODUCCIÓN
    # Estas configuraciones NO afectan el uso local
    SESSION_COOKIE_SECURE = True  # Solo cookies HTTPS
    CSRF_COOKIE_SECURE = True  # Solo cookies HTTPS
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'  # Solo si está configurado
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))  # Solo si está configurado
    SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
    SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
else:
    # Configuraciones para DESARROLLO LOCAL
    # Permiten uso sin HTTPS y facilitan el desarrollo
    SESSION_COOKIE_SECURE = False  # Permite HTTP local
    CSRF_COOKIE_SECURE = False  # Permite HTTP local
    SECURE_SSL_REDIRECT = False  # No fuerza HTTPS en local
    X_FRAME_OPTIONS = 'SAMEORIGIN'  # Permite iframes en desarrollo

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging Configuration
import logging
from pathlib import Path

LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'inventario.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'file_errors': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'errors.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'inventario': {
            'handlers': ['file', 'file_errors', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ============================================================================
# CONFIGURACIÓN DE CACHE
# ============================================================================
# Para DESARROLLO LOCAL: Usa LocMemCache (memoria local) - Rápido y sin dependencias
# Para PRODUCCIÓN: Usa Redis si está disponible (mejor para múltiples workers)
# ============================================================================

# En desarrollo local (DEBUG=True), usar siempre LocMemCache (más rápido y sin dependencias)
# En producción (DEBUG=False), intentar Redis si está explícitamente habilitado
USE_REDIS = os.environ.get('USE_REDIS', 'False').lower() == 'true'

if USE_REDIS and not DEBUG:
    # Solo intentar Redis en producción si está explícitamente habilitado
    REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
    try:
        import redis
        # Intentar conectar a Redis con timeout muy corto
        r = redis.from_url(REDIS_URL, socket_connect_timeout=1, socket_timeout=1)
        r.ping()  # Probar conexión
        CACHES = {
            'default': {
                'BACKEND': 'django_redis.cache.RedisCache',
                'LOCATION': REDIS_URL,
                'OPTIONS': {
                    'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                    'SOCKET_CONNECT_TIMEOUT': 1,  # Timeout de conexión muy corto
                    'SOCKET_TIMEOUT': 1,  # Timeout de operaciones muy corto
                    'IGNORE_EXCEPTIONS': True,  # Si Redis falla, no rompe la app
                },
                'KEY_PREFIX': 'stockex',
                'TIMEOUT': 300,  # 5 minutos por defecto
            }
        }
    except (ImportError, redis.ConnectionError, redis.TimeoutError, Exception):
        # Si Redis falla, usar LocMemCache
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                'LOCATION': 'unique-snowflake',
                'OPTIONS': {
                    'MAX_ENTRIES': 1000,  # Máximo de entradas en cache
                },
                'TIMEOUT': 300,  # 5 minutos por defecto
            }
        }
else:
    # DESARROLLO LOCAL: Usar siempre LocMemCache (rápido, sin dependencias)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'OPTIONS': {
                'MAX_ENTRIES': 1000,  # Máximo de entradas en cache
            },
            'TIMEOUT': 300,  # 5 minutos por defecto
        }
    }

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # Throttling para prevenir abuso de la API
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # Usuarios no autenticados: 100 requests/hora
        'user': '1000/hour',  # Usuarios autenticados: 1000 requests/hora
    },
    # Configuración de renderizado
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # Manejo de excepciones
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    # Schema para Swagger/OpenAPI
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Configuración de drf-spectacular (Swagger/OpenAPI)
SPECTACULAR_SETTINGS = {
    'TITLE': 'STOCKEX API',
    'DESCRIPTION': 'API REST completa para el sistema de gestión de inventario STOCKEX',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api/v1/',
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'Productos', 'description': 'Gestión de productos'},
        {'name': 'Categorías', 'description': 'Gestión de categorías'},
        {'name': 'Ventas', 'description': 'Gestión de ventas'},
        {'name': 'Cotizaciones', 'description': 'Gestión de cotizaciones'},
        {'name': 'Clientes', 'description': 'Gestión de clientes'},
        {'name': 'Proveedores', 'description': 'Gestión de proveedores'},
        {'name': 'Stock', 'description': 'Movimientos y notificaciones de stock'},
    ],
}

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

# Email Configuration (para reportes programados)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # En desarrollo, usar consola
# Para producción, configurar:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'tu-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'tu-password'
DEFAULT_FROM_EMAIL = 'noreply@stockex.com'

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/1')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')

# Configuración de Celery
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Santiago'  # Ajusta según tu zona horaria
CELERY_ENABLE_UTC = True

# Configuración de tareas
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'False') == 'True'  # Para desarrollo/testing
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutos máximo por tarea
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutos soft limit

# Si Redis no está disponible, Celery usará el broker en memoria (solo para desarrollo)
if CELERY_TASK_ALWAYS_EAGER:
    # En modo eager, las tareas se ejecutan sincrónicamente (útil para desarrollo)
    pass
