"""
Constantes del sistema de inventario
Evita el uso de "magic numbers" y strings mágicos en el código
"""

# Límites de stock
STOCK_MINIMO_DEFAULT = 10
STOCK_MAXIMO_DEFAULT = 10000

# Límites de precios
PRECIO_MINIMO = 0
PRECIO_MAXIMO = 999999999  # ~1 billón

# Tamaños de imágenes
IMAGEN_MAX_WIDTH = 800
IMAGEN_MAX_HEIGHT = 800
IMAGEN_QUALITY = 85

# Límites de caracteres
NOMBRE_PRODUCTO_MAX_LENGTH = 200
DESCRIPCION_MAX_LENGTH = 1000
SKU_MAX_LENGTH = 50

# Estados de facturas
ESTADO_FACTURA_PENDIENTE = 'pendiente'
ESTADO_FACTURA_PROCESADA = 'procesada'
ESTADO_FACTURA_RECHAZADA = 'rechazada'

ESTADOS_FACTURA = [
    ESTADO_FACTURA_PENDIENTE,
    ESTADO_FACTURA_PROCESADA,
    ESTADO_FACTURA_RECHAZADA,
]

# Estados de ventas
ESTADO_VENTA_NORMAL = 'normal'
ESTADO_VENTA_CANCELADA = 'cancelada'

# Métodos de pago
METODO_PAGO_EFECTIVO = 'efectivo'
METODO_PAGO_TARJETA = 'tarjeta'
METODO_PAGO_TRANSFERENCIA = 'transferencia'
METODO_PAGO_CREDITO = 'credito'
METODO_PAGO_MIXTO = 'mixto'

METODOS_PAGO = [
    METODO_PAGO_EFECTIVO,
    METODO_PAGO_TARJETA,
    METODO_PAGO_TRANSFERENCIA,
    METODO_PAGO_CREDITO,
    METODO_PAGO_MIXTO,
]

# Estados de cotizaciones
ESTADO_COTIZACION_PENDIENTE = 'pendiente'
ESTADO_COTIZACION_APROBADA = 'aprobada'
ESTADO_COTIZACION_RECHAZADA = 'rechazada'
ESTADO_COTIZACION_VENCIDA = 'vencida'

ESTADOS_COTIZACION = [
    ESTADO_COTIZACION_PENDIENTE,
    ESTADO_COTIZACION_APROBADA,
    ESTADO_COTIZACION_RECHAZADA,
    ESTADO_COTIZACION_VENCIDA,
]

# Estados de cuentas por cobrar
ESTADO_CUENTA_PENDIENTE = 'pendiente'
ESTADO_CUENTA_PARCIAL = 'parcial'
ESTADO_CUENTA_PAGADO = 'pagado'
ESTADO_CUENTA_VENCIDO = 'vencido'
ESTADO_CUENTA_CANCELADO = 'cancelado'

ESTADOS_CUENTA = [
    ESTADO_CUENTA_PENDIENTE,
    ESTADO_CUENTA_PARCIAL,
    ESTADO_CUENTA_PAGADO,
    ESTADO_CUENTA_VENCIDO,
    ESTADO_CUENTA_CANCELADO,
]

# Tipos de movimiento de stock
TIPO_MOVIMIENTO_ENTRADA = 'entrada'
TIPO_MOVIMIENTO_SALIDA = 'salida'
TIPO_MOVIMIENTO_AJUSTE = 'ajuste'
TIPO_MOVIMIENTO_PERDIDA = 'perdida'
TIPO_MOVIMIENTO_DEVOLUCION = 'devolucion'

TIPOS_MOVIMIENTO = [
    TIPO_MOVIMIENTO_ENTRADA,
    TIPO_MOVIMIENTO_SALIDA,
    TIPO_MOVIMIENTO_AJUSTE,
    TIPO_MOVIMIENTO_PERDIDA,
    TIPO_MOVIMIENTO_DEVOLUCION,
]

# Motivos de movimiento
MOTIVO_COMPRA = 'compra'
MOTIVO_VENTA = 'venta'
MOTIVO_AJUSTE_INVENTARIO = 'ajuste_inventario'
MOTIVO_PERDIDA = 'perdida'
MOTIVO_DEVOLUCION_CLIENTE = 'devolucion_cliente'
MOTIVO_DEVOLUCION_PROVEEDOR = 'devolucion_proveedor'
MOTIVO_TRANSFERENCIA = 'transferencia'
MOTIVO_OTRO = 'otro'

# Tamaños de paginación
PAGINACION_DEFAULT = 20
PAGINACION_MAX = 100

# Timeouts de cache (en segundos)
CACHE_TIMEOUT_DEFAULT = 300  # 5 minutos
CACHE_TIMEOUT_LARGO = 3600  # 1 hora
CACHE_TIMEOUT_CORTO = 60  # 1 minuto

# Límites de archivos
TAMANO_MAX_ARCHIVO_MB = 10
TAMANO_MAX_IMAGEN_MB = 5

# Formatos de exportación
FORMATO_EXPORT_PDF = 'pdf'
FORMATO_EXPORT_EXCEL = 'excel'
FORMATO_EXPORT_CSV = 'csv'
FORMATO_EXPORT_JSON = 'json'
FORMATO_EXPORT_XML = 'xml'

FORMATOS_EXPORT = [
    FORMATO_EXPORT_PDF,
    FORMATO_EXPORT_EXCEL,
    FORMATO_EXPORT_CSV,
    FORMATO_EXPORT_JSON,
    FORMATO_EXPORT_XML,
]

# Frecuencias de reportes programados
FRECUENCIA_DIARIO = 'diario'
FRECUENCIA_SEMANAL = 'semanal'
FRECUENCIA_MENSUAL = 'mensual'
FRECUENCIA_PERSONALIZADO = 'personalizado'

FRECUENCIAS_REPORTE = [
    FRECUENCIA_DIARIO,
    FRECUENCIA_SEMANAL,
    FRECUENCIA_MENSUAL,
    FRECUENCIA_PERSONALIZADO,
]

# Tipos de reportes
TIPO_REPORTE_VENTAS = 'ventas'
TIPO_REPORTE_INVENTARIO = 'inventario'
TIPO_REPORTE_STOCK_BAJO = 'stock_bajo'
TIPO_REPORTE_CUENTAS_COBRAR = 'cuentas_cobrar'
TIPO_REPORTE_COMPLETO = 'completo'

TIPOS_REPORTE = [
    TIPO_REPORTE_VENTAS,
    TIPO_REPORTE_INVENTARIO,
    TIPO_REPORTE_STOCK_BAJO,
    TIPO_REPORTE_CUENTAS_COBRAR,
    TIPO_REPORTE_COMPLETO,
]

